// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitHub.VisualStudio.Contrib.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGitHubCommandPackageString = "39d56d2d-30ad-4a94-b950-9a4cd34c2b2b";
        public const string guidGitHubCommandPackageCmdSetString = "c194ca32-569e-4458-af37-b10f9a95b420";
        public const string guidImagesString = "60479cf2-828b-4e7c-9142-f7b26a9c2eda";
        public static Guid guidGitHubCommandPackage = new Guid(guidGitHubCommandPackageString);
        public static Guid guidGitHubCommandPackageCmdSet = new Guid(guidGitHubCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GitHubCommandId = 0x0100;
        public const int GitHubConsoleCommandId = 0x0101;
        public const int cmdidToolWindowCommand = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
